//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coral")]
        public global::System.Drawing.Color Enemy_Color {
            get {
                return ((global::System.Drawing.Color)(this["Enemy_Color"]));
            }
            set {
                this["Enemy_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color Team_Color {
            get {
                return ((global::System.Drawing.Color)(this["Team_Color"]));
            }
            set {
                this["Team_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::System.Windows.Forms.Keys Key_Show_MENU {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Key_Show_MENU"]));
            }
            set {
                this["Key_Show_MENU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SNAPLINE {
            get {
                return ((bool)(this["SNAPLINE"]));
            }
            set {
                this["SNAPLINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ESP_Color {
            get {
                return ((global::System.Drawing.Color)(this["ESP_Color"]));
            }
            set {
                this["ESP_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SNAPLINE_Color {
            get {
                return ((global::System.Drawing.Color)(this["SNAPLINE_Color"]));
            }
            set {
                this["SNAPLINE_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ESP_Size {
            get {
                return ((int)(this["ESP_Size"]));
            }
            set {
                this["ESP_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SNAPLINE_Size {
            get {
                return ((int)(this["SNAPLINE_Size"]));
            }
            set {
                this["SNAPLINE_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ESP_Form {
            get {
                return ((int)(this["ESP_Form"]));
            }
            set {
                this["ESP_Form"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ESP {
            get {
                return ((bool)(this["ESP"]));
            }
            set {
                this["ESP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SNAPLINE_Starting_Point {
            get {
                return ((int)(this["SNAPLINE_Starting_Point"]));
            }
            set {
                this["SNAPLINE_Starting_Point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OVERLAY {
            get {
                return ((bool)(this["OVERLAY"]));
            }
            set {
                this["OVERLAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string AIM_Key {
            get {
                return ((string)(this["AIM_Key"]));
            }
            set {
                this["AIM_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_DISTANCE {
            get {
                return ((bool)(this["Show_DISTANCE"]));
            }
            set {
                this["Show_DISTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AIMBOT {
            get {
                return ((bool)(this["AIMBOT"]));
            }
            set {
                this["AIMBOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color Default_Background_Color {
            get {
                return ((global::System.Drawing.Color)(this["Default_Background_Color"]));
            }
            set {
                this["Default_Background_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AIM_Auto_Fire {
            get {
                return ((bool)(this["AIM_Auto_Fire"]));
            }
            set {
                this["AIM_Auto_Fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CROSSHAIR {
            get {
                return ((bool)(this["CROSSHAIR"]));
            }
            set {
                this["CROSSHAIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CROSSHAIR_Size {
            get {
                return ((int)(this["CROSSHAIR_Size"]));
            }
            set {
                this["CROSSHAIR_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CROSSHAIR_Thickness {
            get {
                return ((int)(this["CROSSHAIR_Thickness"]));
            }
            set {
                this["CROSSHAIR_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color CROSSHAIR_Color {
            get {
                return ((global::System.Drawing.Color)(this["CROSSHAIR_Color"]));
            }
            set {
                this["CROSSHAIR_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AIMOT_Target {
            get {
                return ((int)(this["AIMOT_Target"]));
            }
            set {
                this["AIMOT_Target"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float AIMBOT_Acceleration {
            get {
                return ((float)(this["AIMBOT_Acceleration"]));
            }
            set {
                this["AIMBOT_Acceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Aim_FOV {
            get {
                return ((int)(this["Aim_FOV"]));
            }
            set {
                this["Aim_FOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Draw_Aim_Fov {
            get {
                return ((bool)(this["Draw_Aim_Fov"]));
            }
            set {
                this["Draw_Aim_Fov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Active_Func_Key {
            get {
                return ((int)(this["Active_Func_Key"]));
            }
            set {
                this["Active_Func_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color Default_Fore_Color {
            get {
                return ((global::System.Drawing.Color)(this["Default_Fore_Color"]));
            }
            set {
                this["Default_Fore_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int FPS {
            get {
                return ((int)(this["FPS"]));
            }
            set {
                this["FPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_FPS {
            get {
                return ((bool)(this["Show_FPS"]));
            }
            set {
                this["Show_FPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VSAT {
            get {
                return ((bool)(this["VSAT"]));
            }
            set {
                this["VSAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_Allies {
            get {
                return ((bool)(this["Show_Allies"]));
            }
            set {
                this["Show_Allies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_Name {
            get {
                return ((bool)(this["Show_Name"]));
            }
            set {
                this["Show_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VSYNC {
            get {
                return ((bool)(this["VSYNC"]));
            }
            set {
                this["VSYNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Aim_Filter {
            get {
                return ((int)(this["Aim_Filter"]));
            }
            set {
                this["Aim_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color AIMBOT_FOV_Color {
            get {
                return ((global::System.Drawing.Color)(this["AIMBOT_FOV_Color"]));
            }
            set {
                this["AIMBOT_FOV_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ESP_VISIBLE_TEXT {
            get {
                return ((global::System.Drawing.Color)(this["ESP_VISIBLE_TEXT"]));
            }
            set {
                this["ESP_VISIBLE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ESP_SIZE_TEXT {
            get {
                return ((int)(this["ESP_SIZE_TEXT"]));
            }
            set {
                this["ESP_SIZE_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color ESP_FILLED_BORDER_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["ESP_FILLED_BORDER_COLOR"]));
            }
            set {
                this["ESP_FILLED_BORDER_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ESP_ALLIES_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["ESP_ALLIES_COLOR"]));
            }
            set {
                this["ESP_ALLIES_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Profiles {
            get {
                return ((string)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_PING {
            get {
                return ((bool)(this["Show_PING"]));
            }
            set {
                this["Show_PING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_Text_Border {
            get {
                return ((bool)(this["Show_Text_Border"]));
            }
            set {
                this["Show_Text_Border"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color Default_Color {
            get {
                return ((global::System.Drawing.Color)(this["Default_Color"]));
            }
            set {
                this["Default_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color Normal_Color {
            get {
                return ((global::System.Drawing.Color)(this["Normal_Color"]));
            }
            set {
                this["Normal_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 120, 0")]
        public global::System.Drawing.Color Menu_Border_Color {
            get {
                return ((global::System.Drawing.Color)(this["Menu_Border_Color"]));
            }
            set {
                this["Menu_Border_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FPS_CORNER {
            get {
                return ((int)(this["FPS_CORNER"]));
            }
            set {
                this["FPS_CORNER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AUTO_FIRE_MS {
            get {
                return ((int)(this["AUTO_FIRE_MS"]));
            }
            set {
                this["AUTO_FIRE_MS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Player_Name_Color {
            get {
                return ((global::System.Drawing.Color)(this["Player_Name_Color"]));
            }
            set {
                this["Player_Name_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Player_Ping_Color {
            get {
                return ((global::System.Drawing.Color)(this["Player_Ping_Color"]));
            }
            set {
                this["Player_Ping_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double Menu_Opacity {
            get {
                return ((double)(this["Menu_Opacity"]));
            }
            set {
                this["Menu_Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string FontText {
            get {
                return ((string)(this["FontText"]));
            }
            set {
                this["FontText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R2")]
        public string ControllerButtonAIMBOT {
            get {
                return ((string)(this["ControllerButtonAIMBOT"]));
            }
            set {
                this["ControllerButtonAIMBOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public string ControllerToggleAIMBOT {
            get {
                return ((string)(this["ControllerToggleAIMBOT"]));
            }
            set {
                this["ControllerToggleAIMBOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public string ControllerToggleESP {
            get {
                return ((string)(this["ControllerToggleESP"]));
            }
            set {
                this["ControllerToggleESP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string ControllerToggleSNAPLINE {
            get {
                return ((string)(this["ControllerToggleSNAPLINE"]));
            }
            set {
                this["ControllerToggleSNAPLINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string ControllerToggleVSAT {
            get {
                return ((string)(this["ControllerToggleVSAT"]));
            }
            set {
                this["ControllerToggleVSAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ControllerAIMBOTButtonPressed {
            get {
                return ((bool)(this["ControllerAIMBOTButtonPressed"]));
            }
            set {
                this["ControllerAIMBOTButtonPressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextAntiAliasing {
            get {
                return ((bool)(this["TextAntiAliasing"]));
            }
            set {
                this["TextAntiAliasing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT")]
        public string ControllerToggleCROSSHAIR {
            get {
                return ((string)(this["ControllerToggleCROSSHAIR"]));
            }
            set {
                this["ControllerToggleCROSSHAIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Draw_Enemy_Close {
            get {
                return ((bool)(this["Draw_Enemy_Close"]));
            }
            set {
                this["Draw_Enemy_Close"] = value;
            }
        }
    }
}
